# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48c1bc18cc5be786003ae69fa0aaddc8a72f57dc87e1f0280d424c34b22ff0d7beddf56db84ff85169abd1ce1b93282054598e258d8aaf3834b6c22973ea60b7

test:
  secret_key_base: f8fc15dc34bc551eb42edf38d88cdafe5172414724234f40526b8f29bed3c2d4b5cc448a860187441f144150f46db7f333e46e48d759d6c46ec69b2a872d8433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
